cinemas:
  - name: "Babylon"
    url: "https://babylonberlin.eu/programm"
    type: "babylon"
    google_maps_url: "https://maps.app.goo.gl/mgLCZxrr5rSbaaJJ6"
    title_filters:
      - "Babylon Orchester Berlin"
      - "CinemAperitivo"
      - "Kinderwagenkino"
      - "Live"
      - "Workshop"
      - "Podcast"
      - "Filmmaking"
  - name: "Zoo Palast"
    url: "https://zoopalast.premiumkino.de/programm"
    type: "zoo_palast"
    google_maps_url: "https://maps.app.goo.gl/2LVqzeNwsweC1Fu57"
    title_filters: []

  - name: "Best of Cinema"
    url: "https://www.bestofcinema.de/"
    type: "bestofcinema"
    google_maps_url: null
    title_filters: []
  - name: "Open Air Cinema"
    url: "https://openair-kino.net/category/berlin/"
    type: "openair_kino"
    google_maps_url: null
    title_filters: []

newsletter:
  classical_year_threshold: 2010

tmdb:
  language: "de-DE"

output:
  directory: "output"
  filename_template: "newsletter_{date}.html"
